# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BLT_EXM_app', '0002_quote_quoted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fav',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_quote', to='BLT_EXM_app.Quote'),
        ),
        migrations.AlterField(
            model_name='fav',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_user', to='BLT_EXM_app.User'),
        ),
    ]
