# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BLT_EXM_app', '0003_auto_20170628_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_user', to='BLT_EXM_app.User'),
        ),
    ]
